apiVersion: v1
kind: Service
metadata:
  name: httpd-custom-service
spec:
  selector:
    app: httpd-custom
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001   # Choose any available port on your nodes
