apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sidecar-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-sidecar
  template:
    metadata:
      labels:
        app: nginx-sidecar
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-logs
          mountPath: /var/log/nginx
      - name: log-sidecar
        image: busybox:1.36
        command: ["/bin/sh", "-c", "tail -f /var/log/nginx/*.log"]
        volumeMounts:
        - name: nginx-logs
          mountPath: /var/log/nginx
      volumes:
        - name: nginx-logs
          emptyDir: {}
