apiVersion: v1
kind: Service
metadata:
  name: redis-cache
spec:
  type: NodePort
  selector:
    app: redis-cache
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    nodePort: 30000 # Adjust this as needed