apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv1
  labels:
    type: mongo-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/mnt/disks/local-ssd"
