apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
          - containerPort: 80
        startupProbe:
          httpGet:
            path: /healthz
            port: 80
          initalDelaySeconds: 20
          periodSeconds: 5
        livelinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initalDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initalDelaySeconds: 5
          periodSeconds: 3
          sucessThreshold: 1
