apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
data:
  postgres-user: YWRtaW4= # Base64 encoded username (e.g., admin)
  postgres-password: cGFzc3dvcmQ= # Base64 encoded password (e.g., password)
