apiVersion: v1
kind: Pod
metadata:
  name: my-private-pod
spec:
  containers:
  - name: my-private-image
    image: your-registry.com/your-username/your-image:latest
    imagePullSecrets:
    - name: my-registry-secret
