apiVersion: v1
kind: Service
metadata:
  name: spring-k8s-example-service
spec:
  selector:
    app: spring-k8s-example
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
