apiVersion: apps/v1
kind: Deployment
metadata:
  name: emptydir-deployment
  labels:
    app: empty-dir-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: empty-dir-pod
  template:
    metadata:
      labels:
        app: empty-dir-pod
    spec:
      containers:
      - name: container-1
        image: busybox:1.36
        command: ["/bin/sh", "-c"]
        args: ["date >> /cache/date.txt; sleep 25"]
        volumeMounts:
        - name: cache-volume
          mountPath: /cache
      - name: container-2
        image: busybox:1.36
        command: ["/bin/sh", "-c"]
        args: ["cat /cache/date.txt; sleep 25"]
        volumeMounts:
        - name: cache-volume
          mountPath: /cache
      volumes:
      - name: cache-volume
        emptyDir: {}
