apiVersion: v1
kind: Service
metadata:
  name: nginx-monitoring-service
spec:
  type: NodePort
  selector:
    app: nginx-monitoring
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
  - name: promethus
    protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 30081
